<?php

/**
 * @file
 * Allows administrators to add previous/next pagers to any node type.
 */


/**
 * Implements hook_theme()
 *
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function flippy_theme() {
  return array(
    'flippy' => array(
      'variables' => array(
        'list' => array(),
      ),
      'template' => 'flippy',
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function flippy_form_node_type_form_alter(&$form, $form_state) {
  if (isset($form['type'])) {
    $form['flippy'] = array(
      '#type' => 'fieldset',
      '#title' => t('Flippy settings'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#group' => 'additional_settings',
    );

    $form['flippy']['flippy'] = array(
      '#type' => 'checkbox',
      '#title' => t('Build a pager for this content type'),
      '#default_value' => isset($form['flippy']['flippy']) ? $form['flippy']['flippy'] : variable_get('flippy_' . $form['#node_type']->type, FALSE),
    );

    $form['flippy']['flippy_head'] = array(
      '#type' => 'checkbox',
      '#title' => t('Add semantic previous and next links to the document HEAD'),
      '#default_value' => isset($form['flippy']['flippy_head']) ? $form['flippy']['flippy_head'] : variable_get('flippy_head_' . $form['#node_type']->type, FALSE),
      '#states' => array(
        'visible' => array(   // action to take.
          ':input[name=flippy]' => array('checked' => TRUE),
        ),
      ),
    );
    $form['flippy']['flippy_show_empty'] = array(
      '#type' => 'checkbox',
      '#title' => t('Show empty links'),
      '#default_value' => isset($form['flippy']['flippy_show_empty']) ? $form['flippy']['flippy_show_empty'] : variable_get('flippy_show_empty_' . $form['#node_type']->type, TRUE),
      '#states' => array(
        'visible' => array(
          ':input[name=flippy]' => array('checked' => TRUE),
        ),
      ),
      '#description' => t('If checked, empty links will be rendered even if there isn\'t a node in the sequence. For example, if there is no "next" node, the "next" label will be shown but without a link. If tokens are being used, it is recommended that this be unchecked.'), 
    );

    $form['flippy']['flippy_prev_label'] = array(
      '#type' => 'textfield',
      '#title' => t('Label for "Previous" link'),
      '#size' => 32,
      '#default_value' => isset($form['flippy']['flippy_prev_label']) ? $form['flippy']['flippy_prev_label'] : variable_get('flippy_prev_label_' . $form['#node_type']->type, '‹ ' . t('Previous')),
      '#states' => array(
        'visible' => array(
          ':input[name=flippy]' => array('checked' => TRUE),
        ),
      ),
    );

    $form['flippy']['flippy_next_label'] = array(
      '#type' => 'textfield',
      '#title' => t('Label for "Next" link'),
      '#size' => 32,
      '#default_value' => isset($form['flippy']['flippy_next_label']) ? $form['flippy']['flippy_next_label'] : variable_get('flippy_next_label_' . $form['#node_type']->type, t('Next') . ' ›'),
      '#states' => array(
        'visible' => array(
          ':input[name=flippy]' => array('checked' => TRUE),
        ),
      ),
    );

    $form['flippy']['flippy_firstlast'] = array(
      '#type' => 'checkbox',
      '#title' => t('Show first/last links'),
      '#default_value' => isset($form['flippy']['flippy_firstlast']) ? $form['flippy']['flippy_firstlast'] : variable_get('flippy_firstlast_' . $form['#node_type']->type, FALSE),
      '#states' => array(
        'visible' => array(
          ':input[name=flippy]' => array('checked' => TRUE),
        ),
      ),
    );

    $form['flippy']['flippy_first_label'] = array(
      '#type' => 'textfield',
      '#title' => t('Label for "First" link'),
      '#size' => 32,
      '#default_value' => isset($form['flippy']['flippy_first_label']) ? $form['flippy']['flippy_first_label'] : variable_get('flippy_first_label_' . $form['#node_type']->type, '« ' . t('First')),
      '#states' => array(
        'visible' => array(
          ':input[name=flippy_firstlast]' => array('checked' => TRUE),
          ':input[name=flippy]' => array('checked' => TRUE),

        ),
      ),
    );

    $form['flippy']['flippy_last_label'] = array(
      '#type' => 'textfield',
      '#title' => t('Label for "Last" link'),
      '#size' => 32,
      '#default_value' => isset($form['flippy']['flippy_last_label']) ? $form['flippy']['flippy_last_label'] : variable_get('flippy_last_label_' . $form['#node_type']->type, t('Last') . ' »'),
      '#states' => array(
        'visible' => array(
          ':input[name=flippy_firstlast]' => array('checked' => TRUE),
          ':input[name=flippy]' => array('checked' => TRUE),
        ),
      ),
    );

    $form['flippy']['flippy_random'] = array(
      '#type' => 'checkbox',
      '#title' => t('Show random link'),
      '#default_value' => isset($form['flippy']['flippy_random']) ? $form['flippy']['flippy_random'] : variable_get('flippy_random_' . $form['#node_type']->type, FALSE),
      '#states' => array(
        'visible' => array(   // action to take.
          ':input[name=flippy]' => array('checked' => TRUE),
        ),
      ),
    );

    $form['flippy']['flippy_random_label'] = array(
      '#type' => 'textfield',
      '#title' => t('Label for "Random" link'),
      '#size' => 32,
      '#default_value' => isset($form['flippy']['flippy_random_label']) ? $form['flippy']['flippy_random_label'] : variable_get('flippy_random_label_' . $form['#node_type']->type, 'Random'),
      '#states' => array(
        'visible' => array(
          ':input[name=flippy_random]' => array('checked' => TRUE),
          ':input[name=flippy]' => array('checked' => TRUE),
        ),
      ),
    );
    
    $form['flippy']['flippy_token'] = array(
      '#type' => 'fieldset',
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#title' => t('Browse available tokens'),
      '#states' => array(
        'visible' => array(
          ':input[name=flippy]' => array('checked' => TRUE),
        ),
      ),
    );

    $form['flippy']['flippy_token']['flippy_token_browser'] = array(
      '#theme' => 'token_tree',
      '#token_types' => array('node'),
    );
    
    
    $form['flippy']['flippy_truncate'] = array(
      '#type' => 'textfield',
      '#title' => t('Truncate label length'),
      '#size' => 32,
      '#default_value' => isset($form['flippy']['flippy_truncate']) ? $form['flippy']['flippy_truncate'] : variable_get('flippy_truncate_' . $form['#node_type']->type, NULL),
      '#description' => t('Optionally provide a maximum amount length that link labels can be. Labels will be shortened to this length if they exceed the amount of characters.'),
      '#states' => array(
        'visible' => array(
          ':input[name=flippy]' => array('checked' => TRUE),
        ),
      ),
    );
    
    $form['flippy']['flippy_ellipse'] = array(
      '#type' => 'textfield',
      '#title' => t('Truncate ellipse'),
      '#size' => 32,
      '#default_value' => isset($form['flippy']['flippy_ellipse']) ? $form['flippy']['flippy_ellipse'] : variable_get('flippy_ellipse_' . $form['#node_type']->type, '...'),
      '#description' => t('If a maximum label length is set above, an ellipse can be provided here which will be appended to the label after it is shortened.'),
      '#states' => array(
        'visible' => array(
          ':input[name=flippy]' => array('checked' => TRUE),
        ),
      ),
    );
  }
}

/**
 * Implements hook_field_extra_fields().
 */
function flippy_field_extra_fields() {
  $extra = array();
  foreach (node_type_get_names() as $type => $name) {
    if (variable_get('flippy_'. $type, NULL)) {
      $extra['node'][$type] = array(
        'display' => array(
          'flippy_pager' => array(
            'label' => t('Pager'), 
            'description' => t('Flippy module content pager.'), 
            'weight' => 5,
          ), 
        ),
      );
    }
  }
  return $extra;
}

/**
 * Implements hook_node_view().
 */
function flippy_node_view($node, $view_mode = 'full') {
  // Only add the pager if it should be used for this node's content type.
  if (_flippy_use_pager($node)) {
    $node->content['flippy_pager'] = array(
      '#theme' => 'flippy',
      '#list' => flippy_build_list($node),
    );
    // Add the previous/next elements to the page head, if enable for this
    // content type.
    _flippy_add_head_elements($node);
  }
}

/**
 *  Function that builds the list of nodes
 */
function flippy_build_list($node) {
  $master_list = &drupal_static(__FUNCTION__);
  if (!isset($master_list)) {
    $master_list = array();
  }
  if (!isset($master_list[$node->nid])) {
    // Create a starting-point query object
    $query = db_select('node')
      ->fields('node', array('nid', 'title'))
      ->condition('nid', $node->nid, '!=')
      ->condition('status', 1)
      ->condition('type', $node->type, '=')
      ->range(0, 1);

    $first = clone $query;
    $list['first'] = $first
      ->condition(db_or()
        ->condition('created', $node->created, '<')
        ->condition(db_and()
          ->condition('created', $node->created, '=')
          ->condition('nid', $node->nid, '<')))
      ->orderBy('created', 'ASC')
      ->execute()->fetchAssoc();

    $list['current'] = array(
      'nid' => $node->nid,
      'title' => $node->title,
    );

    $prev = clone $query;
    $list['prev'] = $prev
      ->condition(db_or()
        ->condition('created', $node->created, '<')
        ->condition(db_and()
          ->condition('created', $node->created, '=')
          ->condition('nid', $node->nid, '<')))
      ->orderBy('created', 'DESC')
      ->execute()->fetchAssoc();

    $next = clone $query;
    $list['next'] = $next
      ->condition(db_or()
        ->condition('created', $node->created, '>')
        ->condition(db_and()
          ->condition('created', $node->created, '=')
          ->condition('nid', $node->nid, '>')))
      ->orderBy('created', 'ASC')
      ->execute()->fetchAssoc();

    $last = clone $query;
    $list['last'] = $last
      ->condition(db_or()
        ->condition('created', $node->created, '>')
        ->condition(db_and()
          ->condition('created', $node->created, '=')
          ->condition('nid', $node->nid, '>')))
      ->orderBy('created', 'DESC')
      ->execute()->fetchAssoc();
    
    $random = clone $query;
    $list['random'] = $random
      ->orderRandom()
      ->execute()->fetchAssoc();

    $master_list[$node->nid] = $list;
  }
  return $master_list[$node->nid];
}

/**
 *  Implements template_preprocess_hook()
 */
function template_preprocess_flippy(&$vars) {
  $links = array();
  drupal_add_css(drupal_get_path('module', 'flippy') . '/flippy.css');
  
  // for getting node type
  if ($node = menu_get_object('node')) {
    $vars['node'] = $node;
  }

  // Collect all of the node ids in the list
  $nids = array();
  foreach ($vars['list'] as $item) {
    if (isset($item['nid'])) {
      $nids[] = $item['nid'];
    }
  }
  
  // Load all of the nodes
  $list_nodes = node_load_multiple($nids);

  if ($nav = $vars['list']) {
    if (variable_get('flippy_firstlast_'. $vars['node']->type, NULL)) {
      $links['first'] = array(
        'title' => t(variable_get('flippy_first_label_' . $vars['node']->type, NULL)),
        'href' => empty($nav['first']) ? '' : ('node/' . $nav['first']['nid']),
      );
      $links['last'] = array(
        'title' => t(variable_get('flippy_last_label_' . $vars['node']->type, NULL)),
        'href' => empty($nav['last']) ? '' : ('node/' . $nav['last']['nid']),
      );
    }

    if (variable_get('flippy_random_'. $vars['node']->type, NULL)) {
      $links['random'] = array(
        'title' => t(variable_get('flippy_random_label_' . $vars['node']->type, NULL)),
        'href' => empty($nav['random']) ? '' : ('node/' . $nav['random']['nid']),
      );
    }

    $links['prev'] = array(
      'title' => t(variable_get('flippy_prev_label_' . $vars['node']->type, NULL)),
      'href' => empty($nav['prev']) ? '' : ('node/' . $nav['prev']['nid']),
    );
    $links['next'] = array(
      'title' => t(variable_get('flippy_next_label_' . $vars['node']->type, NULL)),
      'href' => empty($nav['next']) ? '' : ('node/' . $nav['next']['nid']),
    );
      
  }
  
  // Replace any tokens present in the links
  foreach ($links as $key => &$link) {
    if (isset($nav[$key]['nid']) && $nav[$key]['nid']) {
      if (isset($list_nodes[$nav[$key]['nid']])) {
        $link['title'] = token_replace($link['title'], array('node' => $list_nodes[$nav[$key]['nid']]));
      }
    }
  }
  
  // See if we need to truncate labels
  if ($truncate = variable_get('flippy_truncate_' . $vars['node']->type, NULL)) {
    if (is_numeric($truncate)) {
      foreach ($links as $key => &$link) {
        if (strlen($link['title']) > $truncate) {
          $link['title'] = substr($link['title'], 0, $truncate) . variable_get('flippy_ellipse_' . $vars['node']->type, '...');
        }
      }
    }
  }
 
  // Set the order that we want the links to be in
  foreach (array('first', 'prev', 'random', 'next', 'last') as $order) {
    if (isset($links[$order])) {
      $vars['links'][$order] = $links[$order];
    }
  }

  $vars['show_empty'] = variable_get('flippy_show_empty_' . $vars['node']->type, TRUE);
  $vars = array_merge($vars, $vars['list']);
  unset($vars['list']);
  unset($vars['node']);
}


/**
 * Implements hook_block_info().
 */
function flippy_block_info() {
  $blocks = array();
  
  // Provide a pager block that will work for all node types
  $blocks['flippy_pager'] = array(
    'info' => t('Flippy Pager (all node types)'),
    'cache' => DRUPAL_NO_CACHE
  );
  
  // Provide node-type specific pager blocks
  foreach (node_type_get_types() as $type) {
    // See if this node type has pagers enabled
    if (variable_get("flippy_{$type->type}", FALSE)) {
      $blocks["flippy_pager-node_type-{$type->type}"] = array(
        'info' => t('Flippy Pager (@type nodes)', array('@type' => $type->name)),
        'cache' => DRUPAL_NO_CACHE
      );
    }
  }
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function flippy_block_view($delta = '') {
  if (substr($delta, 0, 12) == 'flippy_pager') {
    return flippy_pager_block($delta);
  }
  return NULL;
}

/**
 * Render the Flippy pager block. 
 * 
 * @param $delta
 *   The delta passed into hook_block_view(). This will specify whether
 *   or not we this block should render a pager for all enabled node types
 *   or just the specific type requested.
 * @return
 *   A renderable block array.
 */
function flippy_pager_block($delta = '') {
  // Detect if this pager should be for all nodes or just a given type
  if (strstr($delta, 'flippy_pager-node_type-')) {
    $type = str_replace('flippy_pager-node_type-', '', $delta);
  }
  else {
    $type = NULL;
  }
  
  // Detect if we're viewing a node
  if ($node = menu_get_object('node')) {
    // See if this node matches the type requested
    if (!$type || ($type == $node->type)) {
      // Make sure this node type is still enabled
      if (_flippy_use_pager($node)) {
        // Generate the block
        $block = array(
          'subject' => NULL,
          'content' => theme('flippy', array('list' => flippy_build_list($node))),
        );
        // Set head elements
        _flippy_add_head_elements($node);
        
        return $block;
      }
    }
  }
  
  return NULL;
}

/**
 * Determine if the Flippy pager should be shown for the give node.
 * @param $node
 *   Node to check for pager
 * @return
 *   Boolean: TRUE if pager should be shown, FALSE if not
 */
function _flippy_use_pager($node) {
  if (!is_object($node)) {
    return FALSE;
  }
  return node_is_page($node) && variable_get('flippy_'. $node->type, NULL);
}

/**
 * Add the previous/next elements to the page head, if enable for the content
 * type of the given node.
 *
 * @param $node
 *   Node to add head elements for
 */
function _flippy_add_head_elements($node) {
  if (is_object($node)) {
    if (variable_get('flippy_head_' . $node->type, NULL)) {
      $links = flippy_build_list($node);
      if (!empty($links['prev'])) {
        drupal_add_html_head_link(array(
          'rel' => 'prev',
          'href' => url('node/' . $links['prev']['nid']),
        ));
      }
      if (!empty($links['next'])) {
        drupal_add_html_head_link(array(
          'rel' => 'next',
          'href' => url('node/' . $links['next']['nid']),
        ));
      }
    }
  }
}
